require 'libglade2'

class InputGlade
  include GetText

  attr :glade
  attr :activity
  
  # Generated by ruby-glade-template-create
  def initialize(path_or_data, root = nil, domain = nil, localedir = nil, flag = GladeXML::FILE)
    bindtextdomain(domain, localedir, nil, "UTF-8")
    @glade = GladeXML.new(path_or_data, root, domain, localedir, flag) {|handler| method(handler)}
    
  end
  
  # Receive input from the window (when the user presses Enter or presses 'Log', exit the window and record the input)
  def log_activity(widget)
    @activity = @glade.get_widget("EnterActivity").text
    @glade.get_widget("QuestionWindow").visible = false
    @glade.get_widget("QuestionWindow").destroy
    Gtk.main_quit
  end
end

# Get the activity to log
def get_next_activity
  next_activity_input = InputGlade.new("glade/ChangeActivity.glade", nil, "TimeWatch")
  Gtk.main
  next_activity_input.activity
end

